version: "3.4"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=US/Pacific
    volumes:
      - /home/fran/heimdall/config:/config
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped