version: "3.4"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /home/fran/plex:/config
      - /mnt/FranArchives/Media/Music:/music
      - /mnt/FranArchives/Media/Movies:/movies
      - /mnt/FranArchives/Media/TV_Shows:/tvshows
    restart: always