- name: Create new container automatically selecting the next available vmid.
  community.general.proxmox:
    node: 'franhost'
    api_token_id: 'root@pam!terraform'
    api_token_secret: ''
    api_host: 'https://192.168.0.127:8006/'
    hostname: 'https://192.168.0.127:8006/api2/json'
    ostemplate: 'local:vztmpl/ubuntu-14.04-x86_64.tar.gz'